POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4iLCJpZCI6IjY3YjRjMjk3OTM5NDgyODE4M2EwMTJiZSIsImlhdCI6MTczOTk3OTYxNn0.daSsz4v1HaVzEDKBKZ7uFQRn9DjdR6VUnin41Yp-CKw

{
    "title": "4.22*", 
    "author": "John Doe",
    "url":"example.net",
    "likes":11,
    "userId":"67b4c2979394828183a012be"

}